### PR TITLE
Ducksweeper application

### PR DESCRIPTION
**Pull request by pawlos**
I've created a very rudimentary version of Minesweeper app. This is my first attempt to write app from scratch for DuckOS, so feel free to point out if anything was used not according to how it supposed to be.

image

### CODE REVIEW

**Comment by pawlos** [comment]
I could replace mines with ducks (also my mine icon is very, very bad) and call it Ducksweeper ;). The blueish color seems to resemble water anyway.

As for the feedback, I'll try to collect some notes.

**Comment by byteduck** [comment]
That sounds great, thank you! No worries about the feedback if you didn't already have anything in mind.

**Comment by pawlos** [comment]
@byteduck renamed + new icon. Looks even better IMO
image

**Comment by byteduck** [comment]
Amazing, thank you for this! Looking forward to wasting time with ducksweeper 🙂

**Pull request merged**
