### PR TITLE
duckfetch: Add duckfetch

### PR DESCRIPTION
**Pull request by PF94**
Related to #16

image
(operating system string is hardcoded)

### CODE REVIEW

**Comment by byteduck** [comment]
Looks good, although I think maybe we need some more information about the system before this becomes useful (like a hostname, uptime, resolution, etc).

Out of curiousity, did you look into what porting something like neofetch or screenfetch looks like? I'm not sure if this is something that necessarily needs to be included in the base system, since it doesn't expose any information you can't get from other existing utilities (although we should add a uname syscall & command).

**Comment by PF94** [comment]
> did you look into what porting something like neofetch or screenfetch looks like

Neofetch and Screenfetch are bash-based. Bash's repository does not appear to use CMake making porting it kind of impossible until we have a Serenity-esque "package system".

> (like a hostname, uptime, resolution, etc).

Is the resolution logged anywhere? Also it doesn't seem like duckOS has any hostname functionality.

**Comment by byteduck** [comment]
> Neofetch and Screenfetch are bash-based. Bash's repository does not appear to use CMake making porting it kind of impossible until we have a Serenity-esque "package system".

I'm working on something similar to this, haven't quite fleshed it out fully yet though. I'm working on porting binutils and gcc first (I have gotten binutils to compile, but gcc will require porting a few other things like gmp and mpfr).

> Is the resolution logged anywhere? Also it doesn't seem like duckOS has any hostname functionality.

Resolution can be gotten with an ioctl call on /dev/fb0, as well as opening a connection to Pond and querying it from there. duckOS doesn't have any hostname functionality yet, correct.

**Comment by PF94** [comment]
i'll be putting this on hold until I finish the settings app.

**Pull request closed without merging**
