### PR TITLE
Add preliminary settings application and interface setting applet

### PR DESCRIPTION
**Pull request by PF94**
It's kind of bad but that's because of missing widgets (eg: dropdown menu?) and me not able to figure out how to make ListView functional.

image
(``Pond settings`` option is an early duplicate of ``Interface settings`` I can't get rid of without having to make another trunk)

### CODE REVIEW

**Comment by byteduck** [comment]
Hmm, yeah. It's a little early to merge this, and we don't have a lot of configurable settings yet anyway. Looks good so far though!

**Comment by byteduck** [comment]
Larger picture, I'm thinking I'll probably implement some sort of settings daemon for broadcasting settings changes to applications, seeing as all these settings require restarting the OS to have changes take effect.

**Comment by PF94** [comment]
A daemon would be useful, yeah. At first I was trying to make it look something like this.

image

However the UI library seems to be vague due to a lack of documentation, so I ended up just doing the placeholder UI we currently have.

**Comment by PF94** [comment]
image

Attempted to "polish" the UI despite me having no idea of what I'm doing.

**Comment by PF94** [comment]
closing since i no longer have motivation

**Pull request closed without merging**
