### PR TITLE
Add preliminary wallpaper changing

### PR DESCRIPTION
**Pull request by PF94**
This is done by modifying pond.conf, a file which I created for this purpose, as there is currently no user interface for modifiying the wallpaper. I took code from Theme.cpp.

image

Also, my indenting seems to be borked on CLion, any fixes for that?

### CODE REVIEW

**Comment by PF94** [comment]
Is there a way to request a review?

**Comment by byteduck** [comment]
I was planning on taking a look later tonight 🙂

**Comment by PF94** [comment]
Alright

**Review by byteduck — CHANGES_REQUESTED** [review]
Looks good - the indentation should change though, yes. Looks like you're indenting with spaces rather than tabs, so find that setting in your IDE, change it, and make sure the indentation checks out. Or, for a quick fix, copy the tab character from somewhere in this file and use it to indent your new code.

**Review by byteduck — CHANGES_REQUESTED** [review]
Don't mean to nitpick, but it looks like you've reformatted the whole file, which ended up changing some of the code style (such as spacing around pointers and if statements) to be different than that of the rest of duckOS (Side note, I should write a style guide).

Try reverting this commit and manually fixing the indents on the lines you changed (You could run a find-replace for 4 spaces and replace it with the tab character).

**Comment by PF94** [comment]
I will do that after school, since I have high school.

**Comment by PF94** [comment]
well, this is pretty much done

**Pull request merged**
